version: '3.8'

services:
  app:
    container_name: app-node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - minio
    volumes:
      - .:/var/www/app
    env_file:
      - .env
    stdin_open: true
    tty: true

  db:
    container_name: postgres_db
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=task-hub-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9001:9001"
    env_file:
      - .env
    command: ["server", "--console-address", ":9001", "/data"]
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
    driver: local
