version: '3.8'
services:
  app:
    container_name: app-node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - .:/var/www/app
      - /var/www/app/node_modules
    env_file:
      - .env
  db:
    container_name: postgres_db
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=task-hub-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: